_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 55
            "2":
                - 1
                - 2
                - 3
                - 11
                - 12
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
agent:
    value:
        agent_class: DQN_Nstep
        agent_type: DeepQNstep
        angles: 0
        batch_size: 1000
        dropout: 0
        en_state: 1
        epsilon_decay: 0.99995
        epsilon_min: 0.05
        epsilon_restart: 1
        final_gamma: 0.005
        init_net: 0
        learning_rate: 0.0003
        memory_size: 20000
        n_step: 5
        neurons:
            - 1000
            - 1000
            - 1000
            - 1000
            - 1000
        update_target_net: 500
env:
    value:
        accept_err: -0.35119018
        curriculum_type: MovingThreshold
        err_mitig: 0
        fake_min_energy: -1.320446365758868
        fn_type: incremental_with_fixed_ends
        n_shots: 1000
        noise_models: '["mumbai_median"]'
        noise_values:
            - 0.001
            - 0.005
        num_layers: 40
        num_qubits: 2
        rand_halt: 1
        shift_threshold_ball: 0.0005
        shift_threshold_time: 500
        succ_radius_shift: 10
        succes_switch: -0.35119018
        success_thresh: 25
        switch_episodes: []
        thresholds: []
general:
    value:
        episodes: 10000
non_local_opt:
    value:
        a: 1.2104
        alpha: 0.9531
        beta_1: 0.9414
        beta_2: 0.9983
        c: 0.1039
        gamma: 0.0984
        global_iters: 100
        lamda: 0.9277
        maxfev: 500
        method: SPSA
        optim_alg: "0"
problem:
    value:
        geometry: H .0 .0 .0; H .0 .0 0.7414
        ham_type: H2
        mapping: jordan_wigner
        taper: 1
